MVC/ThucHanh/BaiTap4_63134417/Models/Class1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap4_63134417.Models
{
    public class MailInfor
    {
        public string From { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Password { get; set; }
    }
}

MVC/ThucHanh/BaiTap4_63134417/Models/MailInfor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap4_63134417.Models
{
    public class MailInfor
    {
        public string From { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Password { get; set; }
    }
}

MVC/ThucHanh/BaiTap4_63134417/Controllers/GuiEmail_63134417Controller.cs
using BaiTap4_63134417.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap4_63134417.Controllers
{
    public class GuiEmail_63134417Controller : Controller
    {
        // GET: GuiEmail_63134417
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(MailInfor model)
        {
            System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage();
            mail.From = new System.Net.Mail.MailAddress(model.From);
            mail.To.Add(model.To);
            mail.Subject = model.Subject;
            mail.Body = model.Body;
            mail.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential(model.From, model.Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);
            return RedirectToAction("Index", "Mail");
        }
        public ActionResult Mail()
        {
            return View();
        }
    }
}

MVC/ThucHanh/BaiTap4_63134417/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap4_63134417.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/ThucHanh/BaiTap4_63134417/Views/GuiEmail_63134417/Index.cshtml
@model BaiTap4_63134417.Models.MailInfor

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Index", "GuiEmail_63134417", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal m-5 p-3 w-96 border border-black align-items-center">
    <h4 class="font-bold text-xl uppercase text-center">Chức năng gửi email</h4>
    <hr />

    <div class="flex justify-between items-center w-full my-2">
        @Html.LabelFor(model => model.From, "Gửi từ mail", htmlAttributes: new { @class = "font-bold w-30 text-right" })
        <div class="">
            @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "w-60 px-1 py-1 border border-black rounded" } })
            @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="flex justify-between items-center w-full my-2">
        @Html.LabelFor(model => model.Password, "Mật khẩu", htmlAttributes: new { @class = "font-bold w-30 text-right" })
        <div class="">
            @Html.PasswordFor(model => model.Password, new { @class = "w-60 px-1 py-1 border border-black rounded" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="flex justify-between items-center w-full my-2">
        @Html.LabelFor(model => model.To, "Gửi đến email", htmlAttributes: new { @class = "font-bold w-30 text-right" })
        <div class="">
            @Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "w-60 px-1 py-1 border border-black rounded" } })
            @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="flex justify-between items-center w-full my-2">
        @Html.LabelFor(model => model.Subject, "Tiêu đề", htmlAttributes: new { @class = "font-bold w-30 text-right" })
        <div class="">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "w-60 px-1 py-1 border border-black rounded" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="flex justify-between items-center w-full my-2">
        @Html.LabelFor(model => model.Body, "Nội dung", htmlAttributes: new { @class = "font-bold w-30 text-right" })
        <div class="w-60">
            @Html.TextAreaFor(model => model.Body, new { @class = "w-60 px-1 py-1 border border-black rounded" })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="flex justify-around items-center w-full my-2">
        <input type="submit" value="Gửi" class="px-2 py-1 border border-black bg-gray-200 rounded" />
    </div>
</div>
}

MVC/ThucHanh/BaiTap4_63134417/Views/GuiEmail_63134417/Mail.cshtml
@{
    ViewBag.Title = "Mail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gửi thành công ok !!!?</h2>